services:
  - type: web
    name: school-management-system
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements-render.txt && python manage.py collectstatic --noinput --settings=config.settings.render"
    startCommand: "python manage.py migrate --noinput --settings=config.settings.render && python create_superuser.py && gunicorn config.wsgi --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --max-requests 1000 --max-requests-jitter 50"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.render
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: USE_PAYMENT_OPTIONS
        value: False
      - key: USE_STRIPE
        value: False
      - key: USE_SENTRY
        value: False
      - key: USE_MAILCHIMP
        value: False
      - key: TIME_ZONE
        value: UTC
      - key: IS_DEMO_ENV
        value: True
      - key: DEMO_SUPERUSER_USERNAME
        value: admin
      - key: DEMO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DEMO_SUPERUSER_PASSWORD
        value: admin123
    databases:
      - name: school-management-db

databases:
  - name: school-management-db
    databaseName: school_management
    user: school_user